### ISSUE TITLE
Undefined method 'force_encoding'

### ISSUE THREAD

**Issue by fatmcgav** [datacentred/datacentred-ldap#64]
Following the merge of PR #55, I'm now getting the following error when attempting to use the module on CentOS 6 with Ruby 1.8.7:

```
Debug: Connecting to LDAP server ldaps://localhost:389
Debug: LDAP Search: {:attributes=>["dc", "objectClass"], :base=>"dc=weareact,dc=net"}
Error: /Stage[main]/Remotepost::Ldap/Ldap_entry[dc=weareact,dc=net]: Could not evaluate: undefined method `force_encoding' for "weareact":String
```

**Comment by bilco105** [comment]
Hi @fatmcgav, 

Ruby 1.8.7 has been EOL for over a year, and isn't supported by this module I'm afraid.

**Comment by fatmcgav** [comment]
@bilco105 That's a shame, as this module has worked perfectly with Ruby 1.8.7 and CentOS 6 until that point... 

CentOS 6 is still the main use in our env, so looks like I'm guna have to go looking for a new ldap module, or pin this one at an older commit... :(
